version: '3'

networks:
  securitypoc:
    driver: overlay

services:
  base0:
    image: base
    environment:
      TAG: base0
      PORT: 39000
      HOST: base0
      BASES: base0:39000,base1:39001
      SILENT: 'false'
    networks:
      securitypoc:
        aliases: 
          - base0
    deploy:
      replicas: 1

  base1:
    image: base
    environment:
      TAG: base1
      PORT: 39001
      HOST: base1
      BASES: base0:39000,base1:39001
      SILENT: 'false'
    networks:
      securitypoc:
        aliases: 
          - base1
    deploy:
      replicas: 1
  api:
    image: api
    environment:
      HOST: 'eth0'
      BASES: base0:39000,base1:39001
      SILENT: 'false'
    ports:
      - '3000:3000'
    networks:
      - securitypoc
    deploy:
      replicas: 1
  user:
    image: user
    environment:
      HOST: ' eth0'
      BASES: base0:39000,base1:39001
      SILENT: 'false'
    ports:
      - '57439:57439'
    networks:
      - securitypoc
    deploy:
      replicas: 1
  auth:
    image: auth
    environment:
      HOST: 'eth0'
      BASES: base0:39000,base1:39001
      SILENT: 'false'
    networks:
      - securitypoc 
    deploy:
      replicas: 1
  repl:
    image: repl
    environment:
      REPL_HOST: 0.0.0.0
      HOST: '@eth0'
      BASES: base0:39000,base1:39001
      SILENT: 'false'
    ports:
      - '10001:10001'
    networks:
      - securitypoc
    deploy:
      replicas: 1
  generators:
    image: generators
    environment:
      HOST: 'eth0'
      BASES: base0:39000,base1:39001
      SILENT: 'false'
    networks:
      - securitypoc
    deploy:
      replicas: 1
  email:
    image: email
    environment:
      HOST: 'eth0'
      BASES: base0:39000,base1:39001
      SILENT: 'false'
    networks:
      - securitypoc
    deploy:
      replicas: 1
  sms:
    image: sms
    environment:
      HOST: 'eth0'
      BASES: base0:39000,base1:39001
      SILENT: 'false'
    networks:
      - securitypoc
    deploy:
      replicas: 1

