version: '3'

networks:
  securitypoc:
    driver: overlay

services:
  base0:
    image: base
    environment:
      TAG: base0
      PORT: 39000
      HOST: base0
      BASES: base0:39000,base1:39001
      SILENT: 'false'
    container_name: base0
    networks:
      securitypoc:
        aliases: 
          - base0
    deploy:
      replicas: 1

  base1:
    image: base
    environment:
      TAG: base1
      PORT: 39001
      HOST: base1
      BASES: base0:39000,base1:39001
      SILENT: 'false'
    container_name: base1
    networks:
      securitypoc:
        aliases: 
          - base1
    deploy:
      replicas: 1
  api:
    image: api
    environment:
      HOST: 'api'
      BASES: base0:39000,base1:39001
      SILENT: 'false'
    ports:
      - '3000:3000'
    networks:
      - securitypoc
    deploy:
      replicas: 1
    container_name: api
  user:
    image: user
    environment:
      HOST: ' user'
      BASES: base0:39000,base1:39001
      SILENT: 'false'
    ports:
      - '57439:57439'
    container_name: user
    networks:
      - securitypoc
    deploy:
      replicas: 1
  auth:
    image: auth
    environment:
      HOST: 'auth'
      BASES: base0:39000,base1:39001
      SILENT: 'false'
    networks:
      - securitypoc
    container_name: auth
    deploy:
      replicas: 1
  repl:
    image: repl
    environment:
      HOST: 'repl'
      BASES: base0:39000,base1:39001
      SILENT: 'false'
    container_name: repl
    ports:
      - '10001:10001'
    networks:
      - securitypoc
    deploy:
      replicas: 1
  email:
    image: email
    environment:
      HOST: 'email'
      BASES: base0:39000,base1:39001
      SILENT: 'false'
    container_name: email
    networks:
      - securitypoc
    deploy:
      replicas: 1
  sms:
    image: sms
    environment:
      HOST: 'sms'
      BASES: base0:39000,base1:39001
      SILENT: 'false'
    container_name: sms
    networks:
      - securitypoc
    deploy:
      replicas: 1

