containers :
	$(MAKE) -C shared container
	$(MAKE) -C api container
	$(MAKE) -C base container
	$(MAKE) -C user container
	$(MAKE) -C auth container
	$(MAKE) -C sms container
	$(MAKE) -C repl container
	$(MAKE) -C email container
		
	
	

.PHONY : containers